example:
  build: ./
  restart: always
  mem_limit: 1g
  environment:
    - CONSUL=consul
    - HEALTH_ENDPOINT=health
    - NGINX_CONFIG=/etc/nginx/nginx.conf
    - NODE_START=node app.js
    - PORT=5000
  ports:
    - 80:80
    - 443:443
